# docker-compose.yml
version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pg-demo
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      # хранение БД вне контейнера
      - ./data:/var/lib/postgresql/data
      # SQL-скрипты, которые entrypoint выполнит при первом старте
      - ./init:/docker-entrypoint-initdb.d
